# $FreeBSD$

DISTVERSION=	460.67
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	0

MASTERDIR=	${.CURDIR}/../nvidia-driver
PKGNAMESUFFIX=	-460

.include "${MASTERDIR}/Makefile"
